### ISSUE TITLE
WhereBuilder.single returns incorrect data type if no queryObject given

### ISSUE THREAD

**Issue by bradshja** [balderdashy/waterline-sequel#25]
There is a check in WhereBuilder.single to ensure that criteria are actually passed in as queryObject, and if there are none, it returns an empty string.

This can cause problems because some code that operates on its return value expects an object, which it returns normally.  The result is that calling code can check for a property called query inside the returned object, and get undefined as a result.  This broke some queries for me.

**Comment by bradshja** [comment]
I submitted PR #26 as a possible fix for this.  It fixes my case anyway.

**Comment by dmarcelino** [comment]
Fixed via #26, thanks @bradshja!
