### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by dmarcelino** [balderdashy/waterline-sequel#37]
There are now over 30 commits ([full list](https://github.com/balderdashy/waterline-sequel/compare/v0.2.0...master)) of changes in waterline-sequel and all integration tests pass. Now would be a good time to release 0.3.0.

@particlebanana, would you mind tagging and releasing v0.3.0 of waterline-sequel?

Me, @devinivy, @tjwebb, @rwoverdijk have discussed this over at Slack and we all believe it's a good time to do this.

balderdashy/sails-mysql#206 and balderdashy/sails-postgresql#147 depend on this.

**Comment by RWOverdijk** [comment]
:+1:

**Comment by particlebanana** [comment]
done - next time lets wait to bump the version until we release it so it's easier to see in the commits where each release is.

**Comment by dmarcelino** [comment]
Yeap, I also think that's the best thing to do @particlebanana. Thanks.
