### ISSUE TITLE
Prepare and release 0.3.1

### ISSUE THREAD

**Issue by dmarcelino** [balderdashy/waterline-sequel#43]
Currently sails-postgresql build has a couple of broken tests introduced in 0.3.0 (#39) ~~and we've found a rather critical bug in sails-postgresql that affects people in Netherlands and Italy timezones (probably more) - balderdashy/sails-postgresql#153~~. It's important we get 0.3.1 out soon to address these.

Tasks:
- [x] Fix #39 
- [ ] Bump package.json version to 0.3.1
- [ ] Release to npm

**UPDATE:** it looks like balderdashy/sails-postgresql#153 will need more than just a simple fix and it may even be necessary an API change

**Comment by dmarcelino** [comment]
@particlebanana, when you have a moment please tag and release waterline-sequel 0.3.1, it fixes #39 which is causing a couple of sails-postgresql tests to break. Thanks

cc: @RWOverdijk

**Comment by particlebanana** [comment]
@dmarcelino done!

**Comment by devinivy** [comment]
:) this is some good news.

**Comment by dmarcelino** [comment]
Good stuff! Thanks @particlebanana

**Comment by dmarcelino** [comment]
Sails-postgresql: [![Build Status](https://travis-ci.org/balderdashy/sails-postgresql.svg?branch=master)](https://travis-ci.org/balderdashy/sails-postgresql)
sails-mysql: [![Build Status](https://travis-ci.org/balderdashy/sails-mysql.svg?branch=master)](https://travis-ci.org/balderdashy/sails-mysql)

And a little bonus, waterline-adapter-tests: [![Build Status](https://travis-ci.org/balderdashy/waterline-adapter-tests.svg?branch=master)](https://travis-ci.org/balderdashy/waterline-adapter-tests) (for the 1st time)

Thanks everyone (@RWOverdijk included)! It should be smooth sail in' from now on (hopefully).
