### ISSUE TITLE
Can't find schema

### ISSUE THREAD

**Issue by RWOverdijk** [balderdashy/waterline-sequel#49]
When aliasing table names, the schema can't be found. A recent commit broke this. The commit in question is [dfd06b1f58706e5130d5f9d4237b8b222ae6b0ea](https://github.com/balderdashy/waterline-sequel/commit/dfd06b1f58706e5130d5f9d4237b8b222ae6b0ea).

I'm using a table alias. The actual name of the table is `props_model` and the identifier is `propsmodel`.

**Comment by devinivy** [comment]
Might these be the relevant adapter fixes?
https://github.com/balderdashy/sails-mysql/pull/212
https://github.com/balderdashy/sails-postgresql/pull/158

**Comment by RWOverdijk** [comment]
I don't know, I don't have time to check. Anyway, this works: #50.

**Comment by devinivy** [comment]
I believe the change you're referring to is the breaking change indicated by `0.4.0`.  The adapters need to be updated to work with waterline-sequel `0.4.0`, which is what those two PRs above are for.

**Comment by RWOverdijk** [comment]
Ok.
